variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  DOCKER_TLS_CERTDIR: "/certs"


stages:
  - build


build_image_test:
  stage: build
  image: docker
  services:
    - docker:dind
  rules:
    - if: '$CI_COMMIT_TAG =~ /^test_.*/'
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:    
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" -t "$CI_REGISTRY_IMAGE:test_latest" .
    - docker push $CI_REGISTRY_IMAGE:test_latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

build_image_prod:
  stage: build
  image: docker
  services:
    - docker:dind
  rules:
    - if: '$CI_COMMIT_TAG =~ /^prod_.*/'
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TITLE -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TITLE
    - docker push $CI_REGISTRY_IMAGE:latest

