services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=francesca
      - RABBITMQ_DEFAULT_PASS=francesca
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/

networks:
  default:
    driver: bridge

volumes:
  rabbitmq_data:

