services:

  publisher:
    image: pub_sub:6
    ports:
      - "8000:8000"
    command: fastapi run app/main_pub.py --host 0.0.0.0 --port 8000

  subscriber:
    image: pub_sub:6
    ports:
      - "9100:9100"
    command: fastapi run app/main_sub.py --host 0.0.0.0 --port 9100
