[tool.bean_message]
name = "bean-message"
title= "Bean message"
description = "Microservice for handle the messages between users"
version = "0.0.0"  # Versione del software

[message.it]

send_successfully = "Messaggio inviato con successo"ù
service_unavailable = "Servizio momentaneamente non disponibile"